## üîÜ Importation des librairies

In [1]:
import pandas as pd
from pmaw import PushshiftAPI

## üîÜ The use of API Pushshift 
### 1Ô∏è‚É£ Extraction des posts (583)

In [148]:
posts = api.search_submissions(subreddit="academia",q="mental health", filter=['id','author','author_fullname','title','selftext','score','created_utc','subreddit'])
post_list = [post for post in posts]

107 results available in Pushshift
Total:: Success Rate: 100.00% - Requests: 10 - Batches: 1 - Items Remaining: 48
Total:: Success Rate: 100.00% - Requests: 20 - Batches: 2 - Items Remaining: 28
Total:: Success Rate: 100.00% - Requests: 30 - Batches: 3 - Items Remaining: 16
Total:: Success Rate: 100.00% - Requests: 40 - Batches: 4 - Items Remaining: 9
Total:: Success Rate: 100.00% - Requests: 50 - Batches: 5 - Items Remaining: 6
Total:: Success Rate: 100.00% - Requests: 60 - Batches: 6 - Items Remaining: 4
Total:: Success Rate: 100.00% - Requests: 70 - Batches: 7 - Items Remaining: 2
Total:: Success Rate: 100.00% - Requests: 80 - Batches: 8 - Items Remaining: 1
Total:: Success Rate: 100.00% - Requests: 82 - Batches: 9 - Items Remaining: 0

### 2Ô∏è‚É£ Clean posts

In [149]:
post_df=pd.DataFrame(post_list)
post_df.head(10)

,author,author_fullname,created_utc,id,score,selftext,subreddit,title
0,Zolan0501,t2_3pmu7fda,1589461969,gjm308,1,I can understand that professors are looking o...,academia,Are academics in the United States going to le...
1,ThisisWednesday,t2_r19xq,1589374654,giyioi,1,I'm doing a one-year Taught MSc degree at an \...,academia,People who have dropped out of Masters Degrees...
2,leviaker,t2_3bx7rort,1589311054,gii7uu,1,I am finishing up my masters and it is already...,academia,How to prepare mentally for a PhD
3,leviaker,t2_3bx7rort,1588707983,ge4mt6,1,"Hello,\n\nI am a master's student and have a P...",academia,Bettering Mental health
4,justgonnawingit,t2_5x76h8ew,1587154668,g39mjn,13,I‚Äôm in the last year of my undergrad and I‚Äôm e...,academia,TLDR; should I become a high school teacher or...
5,Vivid-Attempt,t2_67ibwxal,1586823585,g0v1y9,1,"Hello,\n\nI am pursuing a master's degree in c...",academia,Losing motivation on Master Thesis
6,SchroedingersFap,t2_7uw4l,1585087340,foe7fu,1,"Dear Fellow Ivory Tower Folx,\n\nI tried to po...",academia,"Academic ""off my chest"": campus closing, telew..."
7,Psychological_Wave_9,t2_3otc5f98,1594193781,hncrje,1,"Hi all, \n\nPlease help me out. I've been read...",academia,Mental health in Academia - (all countries/pos...
8,Zolan0501,t2_3pmu7fda,1594049537,hm9sdb,1,,academia,"Ph.D. student poll finds mental health, bullyi..."
9,trees_and_lakes,t2_70umkhsv,1593937580,hlj7wb,1,I am speaking from my experiences with mental ...,academia,What can be done to improve mental health in a...

#### date post üìÖ

In [150]:
from datetime import datetime
for i in range(len(post_df)):
    post_df['created_utc'][i]=datetime.utcfromtimestamp(post_df['created_utc'][i]).strftime('%Y-%m-%d %H:%M:%S')

<ipython-input-150-4ec2dffdaa69>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  post_df['created_utc'][i]=datetime.utcfromtimestamp(post_df['created_utc'][i]).strftime('%Y-%m-%d %H:%M:%S')
C:\Users\OMAIMA\anaconda3\envs\myfirstevn\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [151]:
post_df.to_csv('post2_df_by_date.csv', index=False, header=True)

#### sort values by score üïπ

In [152]:
post_df=post_df.sort_values(by='score', ascending=False)
post_df.head(10)

,author,author_fullname,created_utc,id,score,selftext,subreddit,title
21,Astro_Biscuit,t2_8arpjxx,2020-07-18 16:51:56,htjte5,147,This Friday I finally found a fix to a bug in ...,academia,Please celebrate with me! Solved a 2 year over...
49,Adventurous-Mango-34,t2_9x5grh7l,2021-02-04 07:18:17,lca8pd,133,To me this is a personal victory. The outcome ...,academia,I finally stood my ground and pushed for first...
62,gvaniotis,t2_2n6adiox,2019-05-15 17:11:25,bp0lpq,29,,academia,The first international meeting on postgraduat...
85,Stauce52,t2_yjyfc,2019-03-20 14:55:40,b3czqu,25,,academia,A Prominent Economist‚Äôs Death Prompts Talk of ...
61,AlternativeOpinion1,t2_dgjopwa,2019-04-04 12:48:22,b9ca90,23,I am curious to know if anyone else has/is exp...,academia,Mental Health and Academia: Feeling overwhelmed
57,DrSarahBellum,t2_6ost2wll,2021-02-24 15:15:47,lrf7ez,15,I'm days away from submitting my PhD thesis an...,academia,How to break away from PhD advisor?
104,ihateacademia,t2_le1yr,2015-02-16 14:30:48,2w2tes,14,"Seriously, why?\nThere are so many health and ...",academia,Why is there this culture of acceptance around...
4,justgonnawingit,t2_5x76h8ew,2020-04-17 20:17:48,g39mjn,13,I‚Äôm in the last year of my undergrad and I‚Äôm e...,academia,TLDR; should I become a high school teacher or...
67,Bl8_m8,t2_9k1vp5i,2019-10-04 10:55:16,dd5r2t,13,Title's bad but it's genuinely how I feel now....,academia,"I am not in yet, but I am out already (UK)"
12,Zolan0501,t2_3pmu7fda,2020-06-14 20:55:59,h91kkp,11,In order to identify what issues of academia w...,academia,How we the academics can start doing something...

In [153]:
post_df.to_csv('post2_df_by_score.csv', index=False, header=True)

### 3Ô∏è‚É£ Post ids

In [99]:
post_ids=[]
B=post_df['id']
for i in range(len(post_df)):
    post_ids.append(B[i])

In [100]:
len(post_ids)

583

In [101]:
#comment_ids = api.search_submission_comment_ids(ids=post_ids)
#comment_id_list = [c_id for c_id in comment_ids]

In [65]:
#clean_id_comment_df=pd.DataFrame(comment_id_list)
#clean_id_comment_df.head(10)
#clean_id_comment_df.to_csv('clean_id_comment_df.csv', index=False, header=True)

### 4Ô∏è‚É£ Extraction des commentaires (2405)

#### Do not execute this cell ‚ö†

In [157]:
%%time
api = PushshiftAPI()
comments = api.search_comments(subreddit="academia",q="mental health", filter=['id','author','author_fullname','title','body','score','created_utc','subreddit'])
comment_list = [comment for comment in comments]

304 results available in Pushshift
Total:: Success Rate: 100.00% - Requests: 10 - Batches: 1 - Items Remaining: 162
Total:: Success Rate: 100.00% - Requests: 20 - Batches: 2 - Items Remaining: 65
Total:: Success Rate: 100.00% - Requests: 30 - Batches: 3 - Items Remaining: 42
Total:: Success Rate: 100.00% - Requests: 40 - Batches: 4 - Items Remaining: 18
Total:: Success Rate: 100.00% - Requests: 50 - Batches: 5 - Items Remaining: 8
Total:: Success Rate: 100.00% - Requests: 60 - Batches: 6 - Items Remaining: 7
Total:: Success Rate: 100.00% - Requests: 70 - Batches: 7 - Items Remaining: 1
Total:: Success Rate: 100.00% - Requests: 80 - Batches: 8 - Items Remaining: 0
Wall time: 1min 30s

### 5Ô∏è‚É£ Clean comments

In [156]:
comment_df = pd.DataFrame(comment_list)
# preview the comments data
#comment_df=comment_df[['id','author','author_fullname','body','score','created_utc','subreddit']]
comment_df.head(10)

                 author author_fullname  created_utc       id  score subreddit
0  throwawaypassingby01     t2_1cwris90   1587521914  fo5bsd1     16  academia
1           daideadwood     t2_3o5rluay   1586883050  fne4s4h      1  academia
2     Wearable_Robotics     t2_4upuid7u   1586445463  fmwf4zk      1  academia
3        _APizzaMyMind_     t2_3kp0bbce   1586406438  fmv59el      2  academia
4       MerryPipAndTook     t2_1cakd1m2   1590859704  fsbptfh      1  academia
5          KishanMishra     t2_1ocj010m   1590774464  fs80gfj      1  academia
6        down_home_girl        t2_hvafz   1590723117  fs5vp2y      1  academia
7        marigoldthundr     t2_3ma5u16d   1590350426  frp440e      1  academia
8             QualiQuan     t2_6ffih6z8   1590327169  frnu45b      1  academia
9              drhoopoe     t2_5u2n37du   1590274255  frld41e      3  academia

#### date üìÖ

In [136]:
from datetime import datetime
for i in range(len(comment_df)):
    comment_df['created_utc'][i]=datetime.utcfromtimestamp(comment_df['created_utc'][i]).strftime('%Y-%m-%d %H:%M:%S')

C:\Users\OMAIMA\anaconda3\envs\myfirstevn\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
<ipython-input-136-9381f36e61de>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comment_df['created_utc'][i]=datetime.utcfromtimestamp(comment_df['created_utc'][i]).strftime('%Y-%m-%d %H:%M:%S')

In [137]:
comment_df['created_utc'].head(10)

0    2020-05-30 17:34:02
1    2020-05-30 15:54:32
2    2020-05-29 21:36:01
3    2020-05-29 19:08:26
4    2020-05-29 18:08:51
5    2020-05-29 10:47:06
6    2020-05-29 01:29:28
7    2020-05-28 22:57:27
8    2020-05-28 22:52:01
9    2020-05-28 18:20:24
Name: created_utc, dtype: object

In [141]:
comment_df.to_csv ('comment2_df_by_date.csv', index = False, header=True)

In [142]:
comment_df=comment_df.sort_values(by='score', ascending=False)

In [143]:
comment_df.head(10)

,id,author,author_fullname,body,score,created_utc,subreddit
2304,cl6imhb,RedBugs,t2_5zz85,I have friends who've quit their PhDs at vario...,2321,2014-10-11 14:06:29,AskAcademia
1706,ef089f1,ardbeg,t2_4g4ip,Congratulations for making the brave decision ...,158,2019-01-26 11:00:28,AskAcademia
335,g54bxf8,phonograhy,t2_f5gk0,"There's a lot to unpack here, and I think most...",120,2020-09-13 15:10:08,AskAcademia
1156,fdgaeo2,Enzohere,t2_13lnm4,I‚Äôm only in my second year and I can already a...,116,2020-01-07 08:51:08,AskAcademia
1617,eacnwlq,HexesOfVexes,t2_it2bf,The good : Holding that book at the end is the...,106,2018-11-24 09:39:55,AskAcademia
1939,drj7opk,HermanTheKid,NaN,"So I'm not trying to be dismissive, I just wan...",103,2017-12-20 19:07:53,AskAcademia
1583,e7iambw,panchoop,t2_d1a5l,I think your annoyance and exasperation is und...,98,2018-10-10 12:05:42,AskAcademia
782,embbsrf,Sickened_but_curious,t2_pdhpg,"Did you ever hear about ""publish or perish""? ...",90,2019-05-02 13:24:28,AskAcademia
1991,dvb8b5y,failedscientist,t2_ko83j77,How cut throat and evil it really is. I think ...,82,2018-03-07 07:51:55,AskAcademia
1993,dv8vis2,Blufaer1e,t2_grdxp,Start seeing a psychologist now. Seriously. Ev...,74,2018-03-06 02:24:55,AskAcademia

In [144]:
comment_df.to_csv ('comment2_df_by_score.csv', index = False, header=True)