## üîÜ Importation des librairies

In [179]:
import pandas as pd
from pmaw import PushshiftAPI

In [180]:
api=PushshiftAPI()

## üîÜ The use of API Pushshift 
### 1Ô∏è‚É£ Extraction des posts (583)

In [184]:
posts = api.search_submissions(subreddit="academia",q="depression", filter=['id','author','author_fullname','title','selftext','score','created_utc','subreddit'])
post_list = [post for post in posts]

62 results available in Pushshift
Total:: Success Rate: 62.50% - Requests: 16 - Batches: 4 - Items Remaining: 42
Total:: Success Rate: 40.82% - Requests: 49 - Batches: 9 - Items Remaining: 21
Checkpoint:: Success Rate: 49.15% - Requests: 59 - Batches: 10 - Items Remaining: 17
Total:: Success Rate: 50.00% - Requests: 60 - Batches: 11 - Items Remaining: 16
Total:: Success Rate: 54.79% - Requests: 73 - Batches: 13 - Items Remaining: 14
Total:: Success Rate: 53.76% - Requests: 93 - Batches: 17 - Items Remaining: 9
1 results available in Pushshift
Total:: Success Rate: 54.26% - Requests: 94 - Batches: 18 - Items Remaining: 0

### 2Ô∏è‚É£ Clean posts

In [185]:
post_df=pd.DataFrame(post_list)
post_df.head(10)

,author,author_fullname,created_utc,id,score,selftext,subreddit,title
0,trees_and_lakes,t2_70umkhsv,1593937580,hlj7wb,1,I am speaking from my experiences with mental ...,academia,What can be done to improve mental health in a...
1,anxiousphdstudent,t2_74mxmoyr,1593654286,hjo01a,1,"My lab has a history of abusing people, but I ...",academia,Why cant PIs change their abusive behavior?
2,hillywho,t2_3xmy59i4,1591847647,h0rj9t,1,"Hello everyone,\n\nI needed some help with an ...",academia,Need help with academic petition
3,CleanSafety77,t2_68ea85re,1587081238,g2qrss,2,I am over 40 PhD applications so far and did n...,academia,When to give up the PhD dream?
4,rLouW,t2_o894fke,1586195391,fw3cj6,1,"Hello, I'm Louis. I attend the University of ...",academia,Difficult choosing a track for my Master's of ...
5,Ltrfsn,t2_1awfeeeo,1584931019,fncfxk,1,These are a few famous scientists and the age ...,academia,Read and weep
6,Dylbo92,t2_p3dkw,1596919122,i66ct2,1,"First off, apologies if this is in the wrong s...",academia,"Major anxiety and depression, unable to start ..."
7,askingquestionst,t2_6ig6n1ff,1596812482,i5fdbe,1,"Hello,\n\nI am going to open my heart here bec...",academia,Identity crisis by leaving Physics.
8,Movladi_M,t2_4ougwx2x,1595996042,hztxvt,1,"This post has been created in relation to **""A...",academia,Academic community
9,StevePoney,t2_5ls4u3tl,1595347700,hva49r,7,"Hey there, I'm looking for some advice or comm...",academia,PhD applications after quitting previous PhD

#### date post üìÖ

In [186]:
from datetime import datetime
for i in range(len(post_df)):
    post_df['created_utc'][i]=datetime.utcfromtimestamp(post_df['created_utc'][i]).strftime('%Y-%m-%d %H:%M:%S')

<ipython-input-186-4ec2dffdaa69>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  post_df['created_utc'][i]=datetime.utcfromtimestamp(post_df['created_utc'][i]).strftime('%Y-%m-%d %H:%M:%S')
C:\Users\OMAIMA\anaconda3\envs\myfirstevn\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [188]:
post_df.to_csv('post3_df_by_date.csv', index=False, header=True)

#### sort values by score üïπ

In [189]:
post_df=post_df.sort_values(by='score', ascending=False)
post_df.head(10)

,author,author_fullname,created_utc,id,score,selftext,subreddit,title
32,matchgame73,t2_3u15o8lc,2019-10-17 01:36:27,dizb5h,70,To my students:\nI need to apologize. I am not...,academia,An apology to my students from an adjunct
31,Jmadd3,t2_4rh2fpg5,2019-10-25 05:21:08,dmssho,29,"Hey Everyone,\n\nI've been drinking due to dep...",academia,I miss academia and I miss history
24,beautifulcosmos,t2_4p72qr6o,2019-11-06 23:05:57,dsoboj,23,I graduated with my Masters from an Ivy League...,academia,Have any other graduate students encountered b...
30,FragrantAstronomer,t2_4d0yymp4,2019-10-25 18:01:41,dn17ay,23,Anyone know of anything good or active?\n\nI j...,academia,Support groups or forums for former academics?
34,Ltrfsn,t2_1awfeeeo,2019-09-24 06:22:49,d8j8mi,16,Maybe hard to relate to it but I've got pretty...,academia,Is a career in academia even possible with sev...
25,Ltrfsn,t2_1awfeeeo,2019-11-03 10:23:12,dqyl4j,14,Depression is kicking my butt and I'm already ...,academia,Any advice on writers block?
33,Bl8_m8,t2_9k1vp5i,2019-10-04 10:55:16,dd5r2t,13,Title's bad but it's genuinely how I feel now....,academia,"I am not in yet, but I am out already (UK)"
28,mlw19mlw91,t2_2hqedzqe,2019-08-29 17:42:11,cx47dl,10,I was recently told that I would not be given ...,academia,What is your honest opinion on accomodations f...
35,arkana_nightshade,t2_2kqm4dmu,2019-07-11 14:54:47,cbwi4n,8,Greetings to all those reading this!\n\n&amp;#...,academia,Post-PhD Remission of Depression/Anxiety
9,StevePoney,t2_5ls4u3tl,2020-07-21 16:08:20,hva49r,7,"Hey there, I'm looking for some advice or comm...",academia,PhD applications after quitting previous PhD

In [190]:
post_df.to_csv('post3_df_by_score.csv', index=False, header=True)

### 3Ô∏è‚É£ Post ids

In [99]:
post_ids=[]
B=post_df['id']
for i in range(len(post_df)):
    post_ids.append(B[i])

In [100]:
len(post_ids)

583

In [101]:
#comment_ids = api.search_submission_comment_ids(ids=post_ids)
#comment_id_list = [c_id for c_id in comment_ids]

In [65]:
#clean_id_comment_df=pd.DataFrame(comment_id_list)
#clean_id_comment_df.head(10)
#clean_id_comment_df.to_csv('clean_id_comment_df.csv', index=False, header=True)

### 4Ô∏è‚É£ Extraction des commentaires (2405)

#### Do not execute this cell ‚ö†

In [191]:
%%time
api = PushshiftAPI()
comments = api.search_comments(subreddit="academia",q="depression", filter=['id','author','author_fullname','title','body','score','created_utc','subreddit'])
comment_list = [comment for comment in comments]

169 results available in Pushshift
Total:: Success Rate: 100.00% - Requests: 10 - Batches: 1 - Items Remaining: 107
Total:: Success Rate: 100.00% - Requests: 20 - Batches: 2 - Items Remaining: 43
Total:: Success Rate: 100.00% - Requests: 30 - Batches: 3 - Items Remaining: 33
Total:: Success Rate: 100.00% - Requests: 40 - Batches: 4 - Items Remaining: 22
Total:: Success Rate: 100.00% - Requests: 50 - Batches: 5 - Items Remaining: 16
Total:: Success Rate: 100.00% - Requests: 60 - Batches: 6 - Items Remaining: 11
Total:: Success Rate: 100.00% - Requests: 70 - Batches: 7 - Items Remaining: 4
Total:: Success Rate: 100.00% - Requests: 80 - Batches: 8 - Items Remaining: 1
Total:: Success Rate: 100.00% - Requests: 89 - Batches: 9 - Items Remaining: 0
Wall time: 1min 39s

### 5Ô∏è‚É£ Clean comments

In [193]:
comment_df = pd.DataFrame(comment_list)
# preview the comments data
#comment_df=comment_df[['id','author','author_fullname','body','score','created_utc','subreddit']]
comment_df.head(10)

,author,author_fullname,body,created_utc,id,score,subreddit
0,Zolan0501,t2_3pmu7fda,I feel another major issue facing academics is...,1594217961,fxbcjf2,1,academia
1,throwawaypassingby01,t2_1cwris90,"it used to be, but now it's considered more a ...",1594001600,fx25ads,1,academia
2,caramul,t2_2xqnhs17,"I have spoken about this a lot with friends, a...",1593984714,fx1c2nj,1,academia
3,jack27808,t2_liwry,Very sorry to hear this. I'm in a similar situ...,1593380435,fwb084p,1,academia
4,real-nobody,t2_409zb5dk,1. It is never too late to make a change. Of a...,1592503107,fv96mrz,1,academia
5,a_statistician,t2_ptowv,"Start by fixing yourself - therapy, treatment ...",1591188897,fsqq72n,1,academia
6,dl064,t2_69n80,\&gt; as I am trying to read up on the liter...,1591105582,fsmutng,1,academia
7,throwawaypassingby01,t2_1cwris90,Just because someone is good in their field do...,1587521914,fo5bsd1,16,academia
8,Kerokeroppi5,t2_y6vm7,She doesn't respect you.\n\nShe's been married...,1586800758,fnanxkm,1,academia
9,SnowblindAlbino,t2_7ild5,People don't seem to be grasping the reality o...,1586537203,fn088dd,2,academia

#### date üìÖ

In [194]:
from datetime import datetime
for i in range(len(comment_df)):
    comment_df['created_utc'][i]=datetime.utcfromtimestamp(comment_df['created_utc'][i]).strftime('%Y-%m-%d %H:%M:%S')

<ipython-input-194-9381f36e61de>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comment_df['created_utc'][i]=datetime.utcfromtimestamp(comment_df['created_utc'][i]).strftime('%Y-%m-%d %H:%M:%S')
C:\Users\OMAIMA\anaconda3\envs\myfirstevn\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [195]:
comment_df['created_utc'].head(10)

0    2020-07-08 14:19:21
1    2020-07-06 02:13:20
2    2020-07-05 21:31:54
3    2020-06-28 21:40:35
4    2020-06-18 17:58:27
5    2020-06-03 12:54:57
6    2020-06-02 13:46:22
7    2020-04-22 02:18:34
8    2020-04-13 17:59:18
9    2020-04-10 16:46:43
Name: created_utc, dtype: object

In [196]:
comment_df.to_csv ('comment3_df_by_date.csv', index = False, header=True)

In [197]:
comment_df=comment_df.sort_values(by='score', ascending=False)

In [198]:
comment_df.head(10)

,author,author_fullname,body,created_utc,id,score,subreddit
7,throwawaypassingby01,t2_1cwris90,Just because someone is good in their field do...,2020-04-22 02:18:34,fo5bsd1,16,academia
152,Morigain,t2_5zym6,I'm sorry but I this is bs... PhD students are...,2017-01-19 07:52:36,dcmd6v2,14,academia
141,elisedds,t2_inb3m,"Depression should be a clinical diagnosis, not...",2017-06-07 02:41:25,dik8sh7,12,academia
166,invisiblecows,t2_9grwl,"This is a little off-topic, but I feel like I ...",2013-10-24 03:58:26,ccyf9k4,10,academia
30,whatsherface9,t2_kcwom,You are not alone &lt;3\n\nAcademia is not the...,2020-07-26 21:53:04,fzcd7sx,10,academia
150,profbigz,t2_103cfd,I would say that if you are suffering from cli...,2016-11-14 20:37:16,da0a7p4,10,academia
144,sweetsensei,NaN,Grad school is incredibly taxing on mental hea...,2017-08-23 16:40:19,dm0t8ln,9,academia
157,RememberToBackupData,t2_9sgjb,"I'm not a supervisor, but I just want to let y...",2016-03-05 12:18:25,d0og4iv,7,academia
45,Cellar_Royale,t2_617lqcni,"First off, congratulations on the grant!\n\nI ...",2020-11-02 18:26:03,gax5ryv,7,academia
149,pinkpix,t2_dgz7y,"I left after 4.5 years of PhD, depression and ...",2016-09-23 22:03:37,d7zg8ru,7,academia

In [199]:
comment_df.to_csv ('comment3_df_by_score.csv', index = False, header=True)